name: py

on:
 schedule:
 - cron: "*/5 * * * *"

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v2 # checkout the repository content to github runner.
     
    - uses: actions/setup-python@v2
      with:
       python-version: 3.6 #install the python needed
    - run: |
       python Scrapper.py
      env:
       key: ${{ secrets.key }} # if Scrapper.py requires passwords..etc, set it as secrets
    - name: export index
       .... # use crosponding script or actions to help export.
