name: py

on:
 schedule:
  - cron: "*/5 * * * *"

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - name: checkout repo content
     uses: actions/checkout@v2 # checkout the repository content to github runner.
   - name: setup python
     uses: actions/setup-python@v2
     with:
       python-version: 3.6 #install the python needed
   - name: execute py script # run the Scrapper.py to get the latest data
     run: |
       python Scrapper.py
     env:
       key: ${{ secrets.key }} # if Scrapper.py requires passwords..etc, set it as secrets
   - name: export index
      .... # use crosponding script or actions to help export.
