name: update

on:
 schedule:
 #- cron: "*/5 * * * *"
 - cron: "0 20 * * *"

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v2 # checkout the repository content to github runner.
     
    - uses: actions/setup-python@v2
      with:
       python-version: 3.6 #install the python needed
      
       
    - name: Install requirements
      run: |
       pip install -r requirements.txt 
    
  
    - run: |
       python Scrapper.py
      env:
       key: ${{ secrets.GMAIL_PASSWORD }}
       send_to: ismailbenlemsieh@gmail.com 
